# Generated by Django 4.1.3 on 2022-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='s', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
